--!nolint
--!nocheck

--[[
    @link https://github.com/Proton-Utilities/Myriad
	
    @author Proton-Utilities
    @repository Myriad

    This file was automatically @generated with ProCMP, it is not intended for manual editing.
--]]

_P = {
    genDate = __COMPOSER.Insert(__COMPOSER.genDate),
    cfg = __COMPOSER.Insert(__COMPOSER.cfg),
    vers = __COMPOSER.Insert(__COMPOSER.vers)
}

__COMPOSER.Insert(__COMPOSER.build)